// Current Cook County appeal calendar data used by the homepage deadline calendar.
// Use ISO dates for posted windows. Use "N/A" when no current window is posted.
window.APPEAL_DEADLINES = [
    { township: 'Oak Park', start: '2026-05-06', deadline: '2026-06-18' },
    { township: 'Riverside', start: '2026-04-24', deadline: '2026-06-08' },
    { township: 'River Forest', start: '2026-04-20', deadline: '2026-06-02' },
    { township: 'Berwyn', start: '2026-05-20', deadline: '2026-07-06' },
    { township: 'Palos', start: '2026-06-03', deadline: '2026-07-17' },
    { township: 'Cicero', start: '2026-06-17', deadline: '2026-07-31' },
    { township: 'Stickney', start: '2026-06-29', deadline: '2026-08-12' },
    { township: 'Lyons', start: '2026-07-23', deadline: '2026-09-03' },
    { township: 'Bremen', start: 'N/A', deadline: 'N/A' },
    { township: 'Lemont', start: 'N/A', deadline: 'N/A' },
    { township: 'Worth', start: 'N/A', deadline: 'N/A' },
    { township: 'Calumet', start: 'N/A', deadline: 'N/A' },
    { township: 'Proviso', start: 'N/A', deadline: 'N/A' },
    { township: 'Orland', start: 'N/A', deadline: 'N/A' },
    { township: 'Thornton', start: 'N/A', deadline: 'N/A' },
    { township: 'Rich', start: 'N/A', deadline: 'N/A' },
    { township: 'Bloom', start: 'N/A', deadline: 'N/A' },
    { township: 'New Trier', start: '2026-05-07', deadline: '2026-06-22' },
    { township: 'Norwood Park', start: '2026-04-13', deadline: '2026-05-26' },
    { township: 'Rogers Park', start: '2026-04-17', deadline: '2026-06-01' },
    { township: 'Evanston', start: '2026-04-22', deadline: '2026-06-04' },
    { township: 'Lake View', start: '2026-05-28', deadline: '2026-07-13' },
    { township: 'Maine', start: '2026-06-05', deadline: '2026-07-21' },
    { township: 'Elk Grove', start: '2026-06-22', deadline: '2026-08-04' },
    { township: 'West Chicago', start: '2026-07-10', deadline: '2026-08-21' },
    { township: 'Northfield', start: '2026-07-24', deadline: '2026-09-04' },
    { township: 'Barrington', start: 'N/A', deadline: 'N/A' },
    { township: 'Hyde Park', start: 'N/A', deadline: 'N/A' },
    { township: 'Leyden', start: 'N/A', deadline: 'N/A' },
    { township: 'Lake', start: 'N/A', deadline: 'N/A' },
    { township: 'Wheeling', start: 'N/A', deadline: 'N/A' },
    { township: 'Palatine', start: 'N/A', deadline: 'N/A' },
    { township: 'Jefferson', start: 'N/A', deadline: 'N/A' },
    { township: 'Schaumburg', start: 'N/A', deadline: 'N/A' },
    { township: 'North Chicago', start: 'N/A', deadline: 'N/A' },
    { township: 'Niles', start: 'N/A', deadline: 'N/A' },
    { township: 'Hanover', start: 'N/A', deadline: 'N/A' },
    { township: 'South Chicago', start: 'N/A', deadline: 'N/A' }
];
