[project]
name = "property_tax"
requires-python = ">=3.11, <3.13"
version = "0.1.0"
description = "A library for Cook County property tax data processing and analysis."
authors = [
    { name="Vu Nguyen", email="vuchicago@gmail.com" }
]
[tool.setuptools]
packages = ["property_tax"]
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

license = { file="LICENSE" }
readme = "README.md"

dependencies = [
    "faicons",
    "shiny",
    "shinywidgets",
    "plotly==5.23.0",
    "pandas",
    # "geopandas==0.12.2",  # commented out
    "ridgeplot",
    "nbformat==5.10.4",
    "pydantic",
    "scikit-learn",
    "requests",
    "rapidfuzz",
    "pyarrow==14.0.2",
    "seaborn",
    "matplotlib==3.9.2",
    "datasets",
    "streamlit==1.52.1",
    "numpy",
    "folium==0.20.0",
    "watchdog==6.0.0",
    "fuzzywuzzy"
]



