CREATE TABLE IF NOT EXISTS property_addresses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pin TEXT,
  address TEXT NOT NULL,
  normalized_address TEXT NOT NULL,
  taxable_value INTEGER,
  last_appeal_year TEXT,
  certified_land INTEGER,
  certified_building INTEGER,
  home_size REAL,
  year_built REAL,
  last_appeal_status TEXT,
  bedroom_count REAL,
  bathroom_count REAL,
  masonry_type TEXT,
  finished_basement TEXT,
  repair_condition TEXT,
  single_vs_multi_family TEXT,
  neighborhood_code TEXT,
  garage_size TEXT,
  property_class TEXT,
  pin_proration_rate REAL,
  pin10 TEXT,
  latitude REAL,
  longitude REAL,
  latitude_raw TEXT,
  longitude_raw TEXT,
  class_code TEXT,
  condo_unit_sqft REAL,
  condo_building_sqft REAL,
  condo_building_non_units REAL,
  condo_building_pins REAL,
  condo_building_mixed_use TEXT,
  condo_parking_space TEXT,
  condo_common_area TEXT
);
