DROP TABLE IF EXISTS property_addresses;

CREATE TABLE property_addresses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pin TEXT,
  address TEXT NOT NULL,
  normalized_address TEXT NOT NULL,
  taxable_value INTEGER,
  last_appeal_year TEXT,
  certified_land INTEGER,
  certified_building INTEGER,
  home_size REAL,
  year_built REAL,
  last_appeal_status TEXT,
  bedroom_count REAL,
  bathroom_count REAL,
  masonry_type TEXT,
  finished_basement TEXT,
  repair_condition TEXT,
  single_vs_multi_family TEXT,
  neighborhood_code TEXT,
  garage_size TEXT,
  property_class TEXT,
  pin_proration_rate REAL,
  pin10 TEXT,
  latitude REAL,
  longitude REAL,
  class_code TEXT,
  tax_district_code INTEGER,
  municipality_number INTEGER,
  municipality_name TEXT,
  tax_municipality_name TEXT,
  cmap_walkability_total_score REAL,
  cmap_walkability_no_transit_score REAL,
  flood_fs_factor REAL,
  chicago_community_area TEXT,
  condo_unit_sqft REAL,
  condo_building_sqft REAL,
  condo_building_non_units REAL,
  condo_building_pins REAL,
  condo_building_mixed_use INTEGER,
  condo_parking_space INTEGER,
  condo_common_area INTEGER
);
