-- No-op: these columns are already created by 0006_rebuild_property_addresses_full.sql.
-- D1/SQLite does not support ALTER TABLE ADD COLUMN IF NOT EXISTS, so keeping this
-- migration empty prevents duplicate-column failures when applying historical migrations.
