-- No-op: these columns are already present in the current appeals table.
-- D1/SQLite does not support ALTER TABLE ADD COLUMN IF NOT EXISTS, so keeping this
-- migration empty prevents duplicate-column failures when applying historical migrations.
